// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System.Collections.Generic;
using System.Linq;
using ProjectEulerSharp.Utilities;

namespace ProjectEulerSharp.Problems
{
    internal sealed class Problem2 : IProjectEulerSolution
    {
        public string Solve()
        {
            var sum = MathsUtilities.FibonacciGeneratorFast()
                .TakeWhile(x => x < 3999999)
                .Where(fibonacciNumber => fibonacciNumber % 2 == 0)
                .Sum(x=>(int)x);

            return sum.ToString();
        }
    }
}